version: '3.8'

services:
  webtodolist:
    image: webtodolist
    build:
      context: .
      dockerfile: WebToDoList/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=postgres;Username=postgres;Password=postgres
    depends_on:
      - db
    networks:
      - todolist_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - todolist_network

volumes:
  postgres_data:

networks:
  todolist_network:
    driver: bridge
